# Generated by Django 4.1.7 on 2023-03-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='title',
        ),
    ]
