# Generated by Django 4.1.7 on 2023-03-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_bookmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='user',
        ),
    ]
