# Generated by Django 4.1.7 on 2023-03-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_cartmodel_cartitemmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart_table',
        ),
    ]
