# Generated by Django 4.1.7 on 2023-03-31 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_alter_cartmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='bookmodel',
            table=None,
        ),
        migrations.DeleteModel(
            name='CartItemModel',
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookmodel'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ManyToManyField(related_name='carts', through='book.CartItems', to='book.bookmodel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
