# Generated by Django 4.1.7 on 2023-03-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_cart_cartmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmodel',
            table='book_table',
        ),
        migrations.AlterModelTable(
            name='cartitems',
            table='item_table',
        ),
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart_table',
        ),
    ]
