# Generated by Django 4.1.7 on 2023-04-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_orderitems_ordermodel_orderitems_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitems',
            table='orderItems_table',
        ),
    ]
