# Generated by Django 4.1.7 on 2023-04-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_ordermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='Address',
            new_name='address',
        ),
    ]
