# Generated by Django 4.1.7 on 2023-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_rename_address_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
