# Generated by Django 4.1.7 on 2023-03-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
